website_url: /
title: HMZE
description: Beyond Vibe Coding - die Zukunft der Softwareentwicklung
feed_url: feed/
feed_lang: de
feed_since: Fri, 05 Feb 2021 00:00 +0000
logo: /assets/img/logo.jpeg
feed_owner: Sebastian Heide-Meyer zu Erpen und Andr√© Neubauer
feed_contact: podcast@hmze.tech

remote_theme: devpg/minimal
color-scheme: dark

plugins:
  - jekyll-remote-theme      